{
  "MIME": "text/x-makefile",
  "inode_type": "REG",
  "magic_type": "makefile script, ASCII text, with very long lines",
  "mode": "-rw-r--r--",
  "sha1": "1a2b5523f41ff2dcdf81a0a5da4474a492407fbb"
}