{
  "MIME": "application/x-gettext-translation",
  "inode_type": "REG",
  "magic_type": "GNU message catalog (little endian), revision 0.0, 441 messages, Project-Id-Version: inkscape 'The path is generated by applying the '",
  "mode": "-rw-r--r--",
  "sha1": "df5a573ea5359847ea316a87345ca39477139ef6"
}