{
  "MIME": "application/x-gettext-translation",
  "inode_type": "REG",
  "magic_type": "GNU message catalog (little endian), revision 0.0, 441 messages, Project-Id-Version: inkscape 'The path is generated by applying the '",
  "mode": "-rw-r--r--",
  "sha1": "c04bc3c2d1f0a70207ca38bb13ec77b6e842e20a"
}