{
  "MIME": "application/x-gettext-translation",
  "inode_type": "REG",
  "magic_type": "GNU message catalog (little endian), revision 0.0, 343 messages, Project-Id-Version: inkscape 'The path is generated by applying the '",
  "mode": "-rw-r--r--",
  "sha1": "0cedc36732f276fe2a9a8ba72ce1f9d29fc9fc86"
}