{
  "MIME": "application/x-gettext-translation",
  "inode_type": "REG",
  "magic_type": "GNU message catalog (little endian), revision 0.0, 480 messages, Project-Id-Version: inkscape 'The path is generated by applying the '",
  "mode": "-rw-r--r--",
  "sha1": "83549c0c131e329f230f044a9a2fcc034f3cc61a"
}