{
  "MIME": "application/x-gettext-translation",
  "inode_type": "REG",
  "magic_type": "GNU message catalog (little endian), revision 0.0, 483 messages, Project-Id-Version: inkscape 'The path is generated by applying the '",
  "mode": "-rw-r--r--",
  "sha1": "348a0d39541936b58bca4397aec63ad28a43061c"
}